// stl2obj converts an ASCII STL file (the format OpenSCAD emits by
// default) into an OBJ file ready for our renderer's loader.
//
// Coordinate-system bridge: OpenSCAD authors in Z-up (so models read
// naturally in the OpenSCAD preview); our renderer expects Y-up. The
// converter applies a -90° rotation around the X axis at export time:
//
//     (x, y, z)_scad  →  (x, z, -y)_game
//
// This preserves right-handedness, so face winding and lighting stay
// correct. We emit explicit per-face vertex normals (transformed the same
// way) so the OBJ loader doesn't have to recompute them from positions.
package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

type vec3 [3]float32

// scadToGame rotates a SCAD-space vector into game space.
func scadToGame(v vec3) vec3 {
	return vec3{v[0], v[2], -v[1]}
}

func parseVec3(fields []string) (vec3, error) {
	if len(fields) < 3 {
		return vec3{}, fmt.Errorf("expected 3 numbers, got %d fields", len(fields))
	}
	var v vec3
	for i := 0; i < 3; i++ {
		f, err := strconv.ParseFloat(fields[i], 32)
		if err != nil {
			return v, fmt.Errorf("parse %q: %w", fields[i], err)
		}
		v[i] = float32(f)
	}
	return v, nil
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: stl2obj <input.stl> <output.obj>")
		os.Exit(1)
	}
	inPath, outPath := os.Args[1], os.Args[2]

	in, err := os.Open(inPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "open input:", err)
		os.Exit(1)
	}
	defer in.Close()

	var verts []vec3
	var normals []vec3
	type triFace struct {
		v0, v1, v2, n int // 1-indexed for OBJ
	}
	var faces []triFace

	scanner := bufio.NewScanner(in)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)

	var curNormal vec3
	var triBuf [3]vec3
	triLen := 0

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		switch fields[0] {
		case "facet":
			// "facet normal nx ny nz"
			if len(fields) < 5 {
				continue
			}
			n, err := parseVec3(fields[2:5])
			if err != nil {
				fmt.Fprintln(os.Stderr, "facet:", err)
				os.Exit(1)
			}
			curNormal = n
			triLen = 0
		case "vertex":
			if len(fields) < 4 || triLen >= 3 {
				continue
			}
			v, err := parseVec3(fields[1:4])
			if err != nil {
				fmt.Fprintln(os.Stderr, "vertex:", err)
				os.Exit(1)
			}
			triBuf[triLen] = v
			triLen++
		case "endfacet":
			if triLen != 3 {
				continue
			}
			base := len(verts)
			verts = append(verts, triBuf[0], triBuf[1], triBuf[2])
			normals = append(normals, curNormal)
			faces = append(faces, triFace{
				v0: base + 1, v1: base + 2, v2: base + 3,
				n: len(normals), // 1-indexed; matches the just-appended normal
			})
			triLen = 0
		}
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintln(os.Stderr, "scan:", err)
		os.Exit(1)
	}

	if len(faces) == 0 {
		fmt.Fprintln(os.Stderr, "no facets found in", inPath)
		os.Exit(1)
	}

	out, err := os.Create(outPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "create output:", err)
		os.Exit(1)
	}
	defer out.Close()

	w := bufio.NewWriter(out)
	defer w.Flush()

	fmt.Fprintf(w, "# generated by tools/stl2obj from %s\n", inPath)
	fmt.Fprintf(w, "# %d triangles\n", len(faces))

	for _, v := range verts {
		s := scadToGame(v)
		fmt.Fprintf(w, "v %g %g %g\n", s[0], s[1], s[2])
	}
	for _, n := range normals {
		s := scadToGame(n)
		fmt.Fprintf(w, "vn %g %g %g\n", s[0], s[1], s[2])
	}
	for _, f := range faces {
		fmt.Fprintf(w, "f %d//%d %d//%d %d//%d\n", f.v0, f.n, f.v1, f.n, f.v2, f.n)
	}

	fmt.Printf("stl2obj: %d tris  %s → %s\n", len(faces), inPath, outPath)
}
