package render

import (
	"github.com/go-gl/gl/v4.1-core/gl"

	"mountain-mogul/internal/world"
)

// SceneResources owns GPU-side state coupled to a particular World — meshes
// keyed by entity ID and other per-scene previews. Replaced wholesale on every
// scene transition by Renderer.ResetSceneState so resources from a previous
// scenario can't bleed into the next.
//
// Engine-scoped resources (shaders, fonts, the static-batch shells, UI/debug
// VAOs, the dynamic batch for agents) live on Renderer directly and survive
// scene transitions.
type SceneResources struct {
	terrainMesh   *Mesh
	terrainChunks []terrainChunk
	terrainWidth  int
	terrainHeight int
	terrainMinY   float32 // surface min/max Y (skirts excluded), drives topo shader
	terrainMaxY   float32

	// snowSurfaceTex is the GPU mirror of Terrain.Surface — a 1 m
	// resolution RGBA8 texture sampled by terrain.frag for sub-cell
	// features (skier tracks, tree wells). Sized to
	// (Width*PxPerCell, Height*PxPerCell).
	snowSurfaceTex  uint32
	snowSurfaceTexW int32
	snowSurfaceTexH int32

	// groomTex is the GPU mirror of Terrain.Groom, one texel per metre.
	groomTex uint32

	// mogulTex mirrors Terrain.Moguls (R16, one texel per metre) and
	// mogulDirTex its fall lines (RG8, one texel per cell).
	mogulTex, mogulDirTex uint32

	// cellOverlayTex is a per-cell RGBA8 overlay texture (one texel per
	// terrain cell). The terrain shader alpha-blends it over the surface.
	// Used for trail and grooming-route highlights. Linear-filtered so
	// cell edges feather naturally.
	cellOverlayTex uint32

	// Per-corner snow state read by terrain.vert (see terrain_mesh.go),
	// and how far snow and its bumps can rise above the ground, for
	// chunk culling.
	cornerSnowTexA uint32
	cornerSnowTexB uint32
	terrainSnowPad float32
	// Scratch for snow flushes, reused frame to frame: the whole-map
	// textures' source, a tile's, and per-worker cell values.
	snowA, snowB         []float32
	snowTileA, snowTileB []float32
	snowScratch          [][]cellSnow

	// detailTex mirrors Terrain.Detail; 0 when the terrain has none.
	detailTex        uint32
	detailW, detailH int
	detailPad        float32

	// materialTex mirrors Terrain.Material, one byte per detail sample;
	// 0 when the terrain has none. materialSrc is the map it was made
	// from, so an unchanged map isn't uploaded again.
	materialTex          uint32
	materialW, materialH int
	materialSrc          *world.TerrainMaterial
	materialVer          int

	liftUpCables    map[uint64]*Mesh
	liftDownCables  map[uint64]*Mesh
	liftQueueMeshes map[uint64]*Mesh

	// roadMesh is a single quad strip covering every road edge in the
	// world; roadLanesMesh is a parallel mesh of dashed centre-line
	// quads drawn over it in a second pass. Both regenerated wholesale
	// by RebuildRoads whenever the road graph changes.
	roadMesh      *Mesh
	roadLanesMesh *Mesh
	roadGhostMesh *Mesh

	// footpathMesh is every footpath (footpath_mesh.go), rebuilt when
	// World.FootpathsRev moves past footpathRev; footpathGhost is the
	// path being drawn, footpathGhostOK whether it can be laid.
	footpathMesh    *Mesh
	footpathRev     int
	footpathGhost   *Mesh
	footpathGhostOK bool

	// ropeMesh is every rope line (rope_mesh.go), rebuilt when
	// World.RopesRev moves past ropeRev; ropeGhost is the rope being
	// strung, ropeGhostOK whether it can be.
	ropeMesh    *Mesh
	ropeRev     int
	ropeGhost   *Mesh
	ropeGhostOK bool

	// parkingMesh is the asphalt for every painted parking lot and
	// parkingStripesMesh the stall lines over it. Regenerated by
	// RebuildParkingLots.
	// lotGhost and lotGhostStripes preview a lot not yet built (SetLotGhost);
	// lotGhostKey is what they were built for, lotGhostOK whether it fits.
	lotGhost           *Mesh
	lotGhostStripes    *Mesh
	lotGhostKey        lotGhostKey
	lotGhostOK         bool
	parkingMesh        *Mesh
	parkingStripesMesh *Mesh

	ghostBatches   map[uint32]*Batch
	ghostUpCable   *Mesh
	ghostDownCable *Mesh
}

func newSceneResources() *SceneResources {
	return &SceneResources{
		liftUpCables:    make(map[uint64]*Mesh),
		liftDownCables:  make(map[uint64]*Mesh),
		liftQueueMeshes: make(map[uint64]*Mesh),
		ghostBatches:    make(map[uint32]*Batch),
	}
}

// Delete releases every GPU resource owned by the scene.
func (s *SceneResources) Delete() {
	if s.terrainMesh != nil {
		s.terrainMesh.Delete()
		s.terrainMesh = nil
	}
	if s.snowSurfaceTex != 0 {
		gl.DeleteTextures(1, &s.snowSurfaceTex)
		s.snowSurfaceTex = 0
		s.snowSurfaceTexW = 0
		s.snowSurfaceTexH = 0
	}
	if s.cellOverlayTex != 0 {
		gl.DeleteTextures(1, &s.cellOverlayTex)
		s.cellOverlayTex = 0
	}
	if s.groomTex != 0 {
		gl.DeleteTextures(1, &s.groomTex)
		s.groomTex = 0
	}
	for _, tex := range []*uint32{&s.mogulTex, &s.mogulDirTex} {
		if *tex != 0 {
			gl.DeleteTextures(1, tex)
			*tex = 0
		}
	}
	s.materialSrc = nil
	for _, tex := range []*uint32{&s.cornerSnowTexA, &s.cornerSnowTexB, &s.detailTex, &s.materialTex} {
		if *tex != 0 {
			gl.DeleteTextures(1, tex)
			*tex = 0
		}
	}
	for id, m := range s.liftUpCables {
		m.Delete()
		delete(s.liftUpCables, id)
	}
	for id, m := range s.liftDownCables {
		m.Delete()
		delete(s.liftDownCables, id)
	}
	for id, m := range s.liftQueueMeshes {
		m.Delete()
		delete(s.liftQueueMeshes, id)
	}
	for id, b := range s.ghostBatches {
		b.Delete()
		delete(s.ghostBatches, id)
	}
	if s.ghostUpCable != nil {
		s.ghostUpCable.Delete()
		s.ghostUpCable = nil
	}
	if s.ghostDownCable != nil {
		s.ghostDownCable.Delete()
		s.ghostDownCable = nil
	}
	if s.roadMesh != nil {
		s.roadMesh.Delete()
		s.roadMesh = nil
	}
	for _, m := range []**Mesh{&s.footpathMesh, &s.footpathGhost, &s.ropeMesh, &s.ropeGhost} {
		if *m != nil {
			(*m).Delete()
			*m = nil
		}
	}
	s.footpathRev, s.ropeRev = -1, -1
	if s.roadLanesMesh != nil {
		s.roadLanesMesh.Delete()
		s.roadLanesMesh = nil
	}
	if s.roadGhostMesh != nil {
		s.roadGhostMesh.Delete()
		s.roadGhostMesh = nil
	}
	if s.parkingMesh != nil {
		s.parkingMesh.Delete()
		s.parkingMesh = nil
	}
	if s.parkingStripesMesh != nil {
		s.parkingStripesMesh.Delete()
		s.parkingStripesMesh = nil
	}
}
